import React, { useState, useEffect } from 'react';
import { AppConfig, Student } from '../../types';
import { GENERIC_SETUP_PROMPT, validateClassSetupJson } from '../../utils/setupValidator';

interface SettingsModalProps {
  isOpen: boolean;
  config: AppConfig;
  onClose: () => void;
  onSaveConfig: (newConfig: AppConfig) => void;
  onSaveStudents: (newStudents: Student[]) => void;
  onImportFullSetup?: (newStudents: Student[], newConfig: AppConfig) => void;
  onImportTimetable: (timetable: any) => void;
  onImportRoster: (roster: any[]) => void;
  onImportSubjects: (subjects: any) => void;
  onDownloadBackup: () => void;
  onResetClass?: () => void;
}

const PROMPT_TIMETABLE = `I am uploading an image/PDF/screenshot of a class timetable schedule. Please extract all lectures from Monday to Saturday and output ONLY a valid JSON object matching this exact schema with no extra conversational text or markdown codeblocks:

{
  "Monday": [
    { "t": "10:00-10:50", "s": "MATH" },
    { "t": "10:50-11:40", "s": "PHY" }
  ],
  "Tuesday": [
    { "t": "10:00-10:50", "s": "CHEM" }
  ]
}`;

const PROMPT_ROSTER = `I am uploading an image/PDF/screenshot of a student class list or attendance roll call sheet. Please extract all student roll numbers and full names, and output ONLY a valid JSON array matching this exact schema with no extra conversational text or markdown codeblocks:

[
  { "roll": 1, "name": "Alice Smith" },
  { "roll": 2, "name": "Bob Johnson" },
  { "roll": 3, "name": "Charlie Brown" }
]`;

const PROMPT_TEACHERS = `I am uploading an image/PDF/screenshot of subject faculty assignments. Please extract all subject codes, subject full names, and faculty/professor names, and output ONLY a valid JSON object matching this exact schema with no extra conversational text or markdown codeblocks:

{
  "MATH": { "name": "Mathematics", "faculty": "Dr. Smith" },
  "PHY": { "name": "Physics", "faculty": "Prof. Davis" },
  "CHEM": { "name": "Chemistry", "faculty": "Dr. Wilson" }
}`;

export const SettingsModal: React.FC<SettingsModalProps> = ({
  isOpen,
  config,
  onClose,
  onSaveConfig,
  onSaveStudents,
  onImportFullSetup,
  onImportTimetable,
  onImportRoster,
  onImportSubjects,
  onDownloadBackup,
  onResetClass
}) => {
  const [activeTab, setActiveTab] = useState<'smart' | 'manual' | 'backup'>('smart');
  const [jsonText, setJsonText] = useState('');

  // Smart Import Textarea states
  const [fullSetupInput, setFullSetupInput] = useState('');
  const [timetableInput, setTimetableInput] = useState('');
  const [rosterInput, setRosterInput] = useState('');
  const [teachersInput, setTeachersInput] = useState('');
  const [fullSetupError, setFullSetupError] = useState<string | null>(null);

  // Copy status indicators
  const [copiedPrompt, setCopiedPrompt] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen) {
      setJsonText(JSON.stringify(config, null, 2));
    }
  }, [config, isOpen]);

  if (!isOpen) return null;

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedPrompt(label);
    if (navigator.vibrate) navigator.vibrate(10);
    setTimeout(() => setCopiedPrompt(null), 2000);
  };

  const handleApplyFullSetup = () => {
    setFullSetupError(null);
    const result = validateClassSetupJson(fullSetupInput);
    if (!result.success || !result.students || !result.config) {
      setFullSetupError(result.error || "Setup couldn't be imported. Please check the information generated by your AI and try again.");
      return;
    }

    if (onImportFullSetup) {
      onImportFullSetup(result.students, result.config);
    } else {
      onSaveStudents(result.students);
      onSaveConfig(result.config);
    }

    alert('Complete Class Setup Imported & Applied Successfully!');
    setFullSetupInput('');
    onClose();
  };

  const handleApplyTimetable = () => {
    try {
      const parsed = JSON.parse(timetableInput);
      onImportTimetable(parsed);
      alert('Timetable Imported & Applied Successfully!');
      setTimetableInput('');
    } catch (e) {
      alert('Invalid JSON format for Timetable. Check syntax or re-copy AI prompt.');
    }
  };

  const handleApplyRoster = () => {
    try {
      const parsed = JSON.parse(rosterInput);
      if (!Array.isArray(parsed)) {
        alert('Roster must be a JSON array of student objects e.g. [{"roll": 1, "name": "..."}]');
        return;
      }
      onImportRoster(parsed);
      alert('Student Roster Imported & Applied Successfully!');
      setRosterInput('');
    } catch (e) {
      alert('Invalid JSON format for Student Roster. Check syntax or re-copy AI prompt.');
    }
  };

  const handleApplyTeachers = () => {
    try {
      const parsed = JSON.parse(teachersInput);
      onImportSubjects(parsed);
      alert('Teacher & Faculty Details Imported Successfully!');
      setTeachersInput('');
    } catch (e) {
      alert('Invalid JSON format for Faculty details. Check syntax or re-copy AI prompt.');
    }
  };

  const handleSaveManual = () => {
    try {
      const parsed = JSON.parse(jsonText);
      onSaveConfig(parsed);
      alert('Settings Saved!');
      onClose();
    } catch (e) {
      alert("Invalid JSON format. Check syntax.");
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const parsed = JSON.parse(evt.target?.result as string);
        if (parsed.students && Array.isArray(parsed.students)) {
          onSaveStudents(parsed.students);
        }
        if (parsed.config) {
          onSaveConfig(parsed.config);
        } else if (!parsed.students && (parsed.subjects || parsed.timetable)) {
          onSaveConfig(parsed);
        }
        alert("Import Successful!");
        onClose();
      } catch (err) {
        alert("Invalid JSON file format.");
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="modal-overlay visible" onClick={onClose} role="dialog" aria-modal="true" aria-labelledby="settings-modal-title">
      <div className="modal-content" style={{ maxWidth: '780px', height: '88vh' }} onClick={e => e.stopPropagation()}>
        <div className="panel-header" style={{ marginBottom: '0.75rem' }}>
          <div>
            <h3 id="settings-modal-title" className="modal-title" style={{ margin: 0 }}>
              Class Settings & Data Importer
            </h3>
            <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', marginTop: '2px' }}>
              Import Class Setup, Timetables, Rosters & Faculty details
            </p>
          </div>
          <button type="button" className="icon-btn" onClick={onClose} aria-label="Close settings modal">&times;</button>
        </div>

        {/* Tab Navigation */}
        <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem', borderBottom: '1px solid #333', paddingBottom: '0.5rem', overflowX: 'auto', flexShrink: 0 }}>
          <button
            type="button"
            className="btn secondary"
            onClick={() => setActiveTab('smart')}
            style={{ opacity: activeTab === 'smart' ? 1 : 0.6, fontSize: '0.8rem', whiteSpace: 'nowrap' }}
            aria-selected={activeTab === 'smart'}
          >
            AI Smart Importer
          </button>
          <button
            type="button"
            className="btn secondary"
            onClick={() => setActiveTab('manual')}
            style={{ opacity: activeTab === 'manual' ? 1 : 0.6, fontSize: '0.8rem' }}
          >
            Raw Config Editor
          </button>
          <button
            type="button"
            className="btn secondary"
            onClick={() => setActiveTab('backup')}
            style={{ opacity: activeTab === 'backup' ? 1 : 0.6, fontSize: '0.8rem' }}
          >
            Offline Backup & Restore
          </button>
        </div>

        {/* Tab 1: AI Photo/PDF Smart Importer */}
        {activeTab === 'smart' && (
          <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {/* Section 0: Full Class Setup */}
            <div style={{ background: '#161616', border: '1px solid var(--accent-red)', padding: '1rem', borderRadius: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                <div>
                  <h4 style={{ margin: 0, fontSize: '0.9rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    🌟 All-in-One Class Setup Importer
                  </h4>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                    Paste full AI setup JSON (includes students, subjects & timetable)
                  </span>
                </div>
                <button
                  type="button"
                  className="btn secondary"
                  style={{ fontSize: '0.72rem', padding: '0.3rem 0.6rem' }}
                  onClick={() => copyToClipboard(GENERIC_SETUP_PROMPT, 'fullsetup')}
                >
                  {copiedPrompt === 'fullsetup' ? 'Setup Prompt Copied!' : 'Copy Setup Prompt'}
                </button>
              </div>

              <textarea
                placeholder='Paste AI Setup JSON here (e.g. {"className": "...", "students": [...], "timetable": {...}})...'
                value={fullSetupInput}
                onChange={e => {
                  setFullSetupInput(e.target.value);
                  if (fullSetupError) setFullSetupError(null);
                }}
                style={{ width: '100%', height: '80px', fontFamily: 'var(--font-mono)', fontSize: '0.78rem', padding: '0.5rem', marginBottom: '0.5rem', resize: 'none' }}
              />

              {fullSetupError && (
                <div style={{ color: 'var(--accent-red)', fontSize: '0.78rem', marginBottom: '0.5rem' }}>
                  ⚠️ {fullSetupError}
                </div>
              )}

              <button
                type="button"
                className="btn primary"
                style={{ width: '100%', fontSize: '0.8rem', padding: '0.4rem' }}
                onClick={handleApplyFullSetup}
                disabled={!fullSetupInput.trim()}
              >
                Import & Apply Complete Class Setup
              </button>
            </div>

            {/* Section 1: Timetable Import */}
            <div style={{ background: '#161616', border: '1px solid #2a2a2a', padding: '1rem', borderRadius: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                <div>
                  <h4 style={{ margin: 0, fontSize: '0.9rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    1. Class Timetable Importer
                  </h4>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                    Upload timetable screenshot to AI and paste JSON result below
                  </span>
                </div>
                <button
                  type="button"
                  className="btn secondary"
                  style={{ fontSize: '0.72rem', padding: '0.3rem 0.6rem' }}
                  onClick={() => copyToClipboard(PROMPT_TIMETABLE, 'timetable')}
                >
                  {copiedPrompt === 'timetable' ? 'Prompt Copied' : 'Copy AI Prompt'}
                </button>
              </div>

              <textarea
                placeholder='Paste AI JSON result here (e.g. {"Monday": [{"t": "10:00-10:50", "s": "CSA"}]})...'
                value={timetableInput}
                onChange={e => setTimetableInput(e.target.value)}
                style={{ width: '100%', height: '70px', fontFamily: 'var(--font-mono)', fontSize: '0.78rem', padding: '0.5rem', marginBottom: '0.5rem', resize: 'none' }}
              />

              <button
                type="button"
                className="btn primary"
                style={{ width: '100%', fontSize: '0.8rem', padding: '0.4rem' }}
                onClick={handleApplyTimetable}
                disabled={!timetableInput.trim()}
              >
                Import & Update Timetable
              </button>
            </div>

            {/* Section 2: Student Roster List Import */}
            <div style={{ background: '#161616', border: '1px solid #2a2a2a', padding: '1rem', borderRadius: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                <div>
                  <h4 style={{ margin: 0, fontSize: '0.9rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    2. Student Roster List Importer
                  </h4>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                    Upload student list PDF/Image to AI and paste student JSON array below
                  </span>
                </div>
                <button
                  type="button"
                  className="btn secondary"
                  style={{ fontSize: '0.72rem', padding: '0.3rem 0.6rem' }}
                  onClick={() => copyToClipboard(PROMPT_ROSTER, 'roster')}
                >
                  {copiedPrompt === 'roster' ? 'Prompt Copied' : 'Copy AI Prompt'}
                </button>
              </div>

              <textarea
                placeholder='Paste AI JSON array here (e.g. [{"roll": 1, "name": "Anshu Raj"}])...'
                value={rosterInput}
                onChange={e => setRosterInput(e.target.value)}
                style={{ width: '100%', height: '70px', fontFamily: 'var(--font-mono)', fontSize: '0.78rem', padding: '0.5rem', marginBottom: '0.5rem', resize: 'none' }}
              />

              <button
                type="button"
                className="btn primary"
                style={{ width: '100%', fontSize: '0.8rem', padding: '0.4rem' }}
                onClick={handleApplyRoster}
                disabled={!rosterInput.trim()}
              >
                Import & Update Student Roster
              </button>
            </div>

            {/* Section 3: Teacher & Faculty Details Import */}
            <div style={{ background: '#161616', border: '1px solid #2a2a2a', padding: '1rem', borderRadius: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                <div>
                  <h4 style={{ margin: 0, fontSize: '0.9rem', color: '#fff', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    3. Teacher & Faculty Details Importer
                  </h4>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                    Upload subject faculty list to AI and paste subject JSON object below
                  </span>
                </div>
                <button
                  type="button"
                  className="btn secondary"
                  style={{ fontSize: '0.72rem', padding: '0.3rem 0.6rem' }}
                  onClick={() => copyToClipboard(PROMPT_TEACHERS, 'teachers')}
                >
                  {copiedPrompt === 'teachers' ? 'Prompt Copied' : 'Copy AI Prompt'}
                </button>
              </div>

              <textarea
                placeholder='Paste AI JSON object here (e.g. {"CSA": {"name": "...", "faculty": "..."}})...'
                value={teachersInput}
                onChange={e => setTeachersInput(e.target.value)}
                style={{ width: '100%', height: '70px', fontFamily: 'var(--font-mono)', fontSize: '0.78rem', padding: '0.5rem', marginBottom: '0.5rem', resize: 'none' }}
              />

              <button
                type="button"
                className="btn primary"
                style={{ width: '100%', fontSize: '0.8rem', padding: '0.4rem' }}
                onClick={handleApplyTeachers}
                disabled={!teachersInput.trim()}
              >
                Import & Update Faculty Details
              </button>
            </div>
          </div>
        )}

        {/* Tab 2: Manual Config Textarea */}
        {activeTab === 'manual' && (
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 }}>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
              Edit raw JSON configuration directly:
            </p>
            <textarea
              value={jsonText}
              onChange={e => setJsonText(e.target.value)}
              style={{ flex: 1, fontFamily: 'monospace', fontSize: '0.8rem', minHeight: '220px', resize: 'none' }}
            />
            <button className="btn primary" style={{ marginTop: '1rem' }} onClick={handleSaveManual}>
              Save Raw Changes
            </button>
          </div>
        )}

        {/* Tab 3: Backup & Restore */}
        {activeTab === 'backup' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', flex: 1 }}>
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '0.35rem' }}>
                Download Complete Offline Backup
              </label>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>
                Saves an offline timestamped JSON backup of all student roster stats and subjects to your computer.
              </p>
              <button className="btn primary" style={{ width: '100%' }} onClick={onDownloadBackup}>
                Download Backup (.json)
              </button>
            </div>

            <div style={{ borderTop: '1px solid #333', paddingTop: '1rem' }}>
              <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '0.35rem' }}>
                Restore Backup / Import Config
              </label>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>
                Upload a JSON backup file to restore your configuration instantly.
              </p>
              <input
                type="file"
                id="config-upload-input"
                accept=".json"
                style={{ display: 'none' }}
                onChange={handleFileUpload}
              />
              <button
                className="btn"
                style={{ width: '100%' }}
                onClick={() => document.getElementById('config-upload-input')?.click()}
              >
                Restore JSON File
              </button>
            </div>

            {onResetClass && (
              <div style={{ borderTop: '1px solid #333', paddingTop: '1rem' }}>
                <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--accent-red)', marginBottom: '0.35rem' }}>
                  Reset All Class Data
                </label>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>
                  Clears the current roster and configuration, returning the app to the initial setup screen.
                </p>
                <button
                  className="btn"
                  style={{ width: '100%', borderColor: 'rgba(255,59,48,0.5)', color: 'var(--accent-red)' }}
                  onClick={() => {
                    onResetClass();
                    onClose();
                  }}
                >
                  ⚠️ Reset Class & Return to Setup
                </button>
              </div>
            )}
          </div>
        )}

        <div style={{ marginTop: '1rem', textAlign: 'right', borderTop: '1px solid #333', paddingTop: '0.5rem' }}>
          <button type="button" className="btn" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
