import React, { useState } from 'react';
import { Student, AppConfig } from '../types';
import { GENERIC_SETUP_PROMPT, validateClassSetupJson } from '../utils/setupValidator';

interface InitialSetupProps {
  onCompleteSetup: (students: Student[], config: AppConfig) => void;
  onOpenAddModal?: () => void;
}

export const InitialSetup: React.FC<InitialSetupProps> = ({
  onCompleteSetup,
  onOpenAddModal
}) => {
  const [jsonInput, setJsonInput] = useState('');
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const handleCopyPrompt = () => {
    navigator.clipboard.writeText(GENERIC_SETUP_PROMPT);
    setCopiedPrompt(true);
    if (navigator.vibrate) navigator.vibrate(10);
    setTimeout(() => setCopiedPrompt(false), 2000);
  };

  const handleImport = () => {
    setErrorMessage(null);
    const result = validateClassSetupJson(jsonInput);
    if (!result.success || !result.students || !result.config) {
      setErrorMessage(result.error || "Setup couldn't be imported. Please check the information generated by your AI and try again.");
      if (navigator.vibrate) navigator.vibrate([20, 50, 20]);
      return;
    }

    onCompleteSetup(result.students, result.config);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (evt) => {
      const content = evt.target?.result as string;
      const result = validateClassSetupJson(content);
      if (result.success && result.students && result.config) {
        onCompleteSetup(result.students, result.config);
      } else {
        setErrorMessage(result.error || "Setup couldn't be imported from this file. Please check the file format.");
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="setup-container" role="main" aria-label="First time class setup">
      <div className="panel setup-card">
        <div className="setup-header">
          <div className="setup-icon" aria-hidden="true">🏫</div>
          <h2>Set Up Your Class</h2>
          <p className="setup-subtitle">
            Welcome! To get started, configure your student roster and schedule using our guided AI setup.
          </p>
        </div>

        <div className="setup-steps">
          {/* Step 1 */}
          <div className="setup-step-item">
            <div className="step-badge" aria-hidden="true">1</div>
            <div className="step-content">
              <div className="step-title">Copy AI Setup Prompt</div>
              <p className="step-desc">
                Copy our standardized setup prompt to your clipboard.
              </p>
              <button
                type="button"
                className={`btn ${copiedPrompt ? 'primary active-copied-btn' : 'secondary'} setup-action-btn`}
                onClick={handleCopyPrompt}
                aria-label="Copy AI Setup prompt to clipboard"
              >
                {copiedPrompt ? (
                  <>
                    <svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor">
                      <path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"/>
                    </svg>
                    Setup prompt copied!
                  </>
                ) : (
                  <>
                    <svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor">
                      <path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z" />
                    </svg>
                    Copy Setup Prompt
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Step 2 */}
          <div className="setup-step-item">
            <div className="step-badge" aria-hidden="true">2</div>
            <div className="step-content">
              <div className="step-title">Paste into Your Favorite AI</div>
              <p className="step-desc">
                Open any AI tool, paste the copied prompt, and attach your student list, timetable, or photo/PDF:
              </p>
              <div className="ai-chips">
                <span className="ai-chip">ChatGPT</span>
                <span className="ai-chip">Gemini</span>
                <span className="ai-chip">Claude</span>
                <span className="ai-chip">Any LLM</span>
              </div>
            </div>
          </div>

          {/* Step 3 */}
          <div className="setup-step-item">
            <div className="step-badge" aria-hidden="true">3</div>
            <div className="step-content">
              <div className="step-title">Paste & Import Result</div>
              <p className="step-desc">
                Paste the JSON structure returned by the AI below:
              </p>
              <textarea
                className="setup-textarea"
                placeholder='Paste generated JSON here (e.g. {"className": "...", "students": [...]})...'
                value={jsonInput}
                onChange={e => {
                  setJsonInput(e.target.value);
                  if (errorMessage) setErrorMessage(null);
                }}
                aria-label="Paste AI generated class setup JSON here"
              />

              {errorMessage && (
                <div className="setup-error-banner" role="alert" aria-live="assertive">
                  <span className="error-icon" aria-hidden="true">⚠️</span>
                  <span>{errorMessage}</span>
                </div>
              )}

              <div className="setup-buttons-grid">
                <button
                  type="button"
                  className="btn primary setup-primary-btn"
                  onClick={handleImport}
                  disabled={!jsonInput.trim()}
                  aria-label="Save class setup and start app"
                >
                  🚀 Save Setup & Start
                </button>
                <div className="setup-secondary-actions">
                  <label className="btn secondary file-restore-btn" tabIndex={0}>
                    📁 Restore Backup File
                    <input
                      type="file"
                      accept=".json"
                      style={{ display: 'none' }}
                      onChange={handleFileUpload}
                      aria-label="Upload JSON backup file"
                    />
                  </label>
                  {onOpenAddModal && (
                    <button
                      type="button"
                      className="btn secondary manual-add-btn"
                      onClick={onOpenAddModal}
                      aria-label="Add first student manually"
                    >
                      + Add Manually
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
