import { Student, AppConfig } from '../types';
import { formatTitleCase } from '../hooks/useAttendance';

export interface ValidationResult {
  success: boolean;
  error?: string;
  students?: Student[];
  config?: AppConfig;
}

export const GENERIC_SETUP_PROMPT = `I want to set up my class attendance and timetable in my attendance tracker application.

Please organize all my class data into a single valid JSON object.

Here is my raw class information:
[PASTE YOUR STUDENT LIST, ROLL NUMBERS, CLASS/SECTION NAME, SUBJECTS, FACULTY, AND TIMETABLE HERE]

Please extract and format all the information into ONLY a valid JSON object matching this exact schema:

{
  "className": "Class / Section / Semester Name",
  "students": [
    { "roll": 1, "name": "Student Full Name" },
    { "roll": 2, "name": "Student Full Name" }
  ],
  "subjects": {
    "SUB_CODE": { "name": "Subject Full Name", "faculty": "Teacher / Faculty Name" }
  },
  "timetable": {
    "Monday": [
      { "t": "10:00-10:50", "s": "SUB_CODE" }
    ],
    "Tuesday": [],
    "Wednesday": [],
    "Thursday": [],
    "Friday": [],
    "Saturday": []
  }
}

Instructions:
1. Extract all supplied students accurately. Preserve full names and exact spellings.
2. If roll numbers are provided, preserve them. If not provided, assign sequential integer roll numbers starting from 1. Ensure roll numbers are unique.
3. Extract class/section/semester name if provided.
4. Extract subject codes, full subject names, and faculty names if provided.
5. Extract the class timetable schedule with start-end times (format: "HH:MM-HH:MM") and subject codes.
6. If subjects or timetable are not provided, leave them as empty objects {} without inventing fake data.
7. Do NOT invent missing student names or fake data.
8. Return ONLY the raw JSON object with no conversational text, explanations, or surrounding markdown formatting.`;

export const validateClassSetupJson = (rawInput: string): ValidationResult => {
  if (!rawInput || !rawInput.trim()) {
    return {
      success: false,
      error: "Setup couldn't be imported. Input is empty. Please paste the JSON generated by your AI."
    };
  }

  // Strip markdown code fences if AI wrapped the output in ```json ... ```
  let cleaned = rawInput.trim();
  cleaned = cleaned.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();

  let parsed: any;
  try {
    parsed = JSON.parse(cleaned);
  } catch (e) {
    return {
      success: false,
      error: "Setup couldn't be imported. Please check the information generated by your AI and try again."
    };
  }

  if (!parsed || (typeof parsed !== 'object' && !Array.isArray(parsed))) {
    return {
      success: false,
      error: "Setup couldn't be imported. Please check the information generated by your AI and try again."
    };
  }

  // Extract raw students list
  let rawStudents: any[] = [];
  if (Array.isArray(parsed)) {
    rawStudents = parsed;
  } else if (Array.isArray(parsed.students)) {
    rawStudents = parsed.students;
  } else if (Array.isArray(parsed.roster)) {
    rawStudents = parsed.roster;
  } else {
    return {
      success: false,
      error: "Setup couldn't be imported. No student list was found. Please ensure the AI included a 'students' list."
    };
  }

  // Validate student list is not empty
  if (rawStudents.length === 0) {
    return {
      success: false,
      error: "Setup couldn't be imported. Student roster cannot be empty."
    };
  }

  // Validate each student and detect duplicates
  const seenRolls = new Set<number>();
  const seenNames = new Set<string>();
  const sanitizedStudents: Student[] = [];

  for (let i = 0; i < rawStudents.length; i++) {
    const item = rawStudents[i];
    if (!item || typeof item !== 'object') {
      return {
        success: false,
        error: `Setup couldn't be imported. Student #${i + 1} is invalid.`
      };
    }

    // Name validation
    if (typeof item.name !== 'string' || !item.name.trim()) {
      return {
        success: false,
        error: `Setup couldn't be imported. Student #${i + 1} has a missing or empty name.`
      };
    }

    const trimmedName = item.name.trim();

    // Duplicate name check
    const normalizedName = trimmedName.toLowerCase();
    if (seenNames.has(normalizedName)) {
      return {
        success: false,
        error: `Setup couldn't be imported. Duplicate student name detected: "${trimmedName}".`
      };
    }
    seenNames.add(normalizedName);

    // Roll number validation
    let roll: number;
    if (typeof item.roll === 'number' && Number.isInteger(item.roll) && item.roll > 0) {
      roll = item.roll;
    } else if (typeof item.roll === 'string' && !isNaN(parseInt(item.roll, 10)) && parseInt(item.roll, 10) > 0) {
      roll = parseInt(item.roll, 10);
    } else if (item.roll === undefined || item.roll === null) {
      roll = i + 1;
    } else {
      return {
        success: false,
        error: `Setup couldn't be imported. Student "${trimmedName}" has an invalid roll number.`
      };
    }

    // Duplicate roll number check
    if (seenRolls.has(roll)) {
      return {
        success: false,
        error: `Setup couldn't be imported. Duplicate student roll number #${roll} detected.`
      };
    }
    seenRolls.add(roll);

    sanitizedStudents.push({
      roll,
      name: formatTitleCase(trimmedName),
      p: false
    });
  }

  // Sort students by roll number
  sanitizedStudents.sort((a, b) => a.roll - b.roll);

  // Validate and sanitize Config
  const semesterName = typeof parsed.className === 'string' && parsed.className.trim()
    ? parsed.className.trim()
    : typeof parsed.semesterName === 'string' && parsed.semesterName.trim()
    ? parsed.semesterName.trim()
    : '';

  const subjects: Record<string, { name: string; faculty?: string }> = {};
  if (parsed.subjects && typeof parsed.subjects === 'object' && !Array.isArray(parsed.subjects)) {
    Object.keys(parsed.subjects).forEach(key => {
      const sub = parsed.subjects[key];
      if (sub && typeof sub === 'object') {
        subjects[key] = {
          name: typeof sub.name === 'string' ? formatTitleCase(sub.name) : key,
          faculty: typeof sub.faculty === 'string' ? formatTitleCase(sub.faculty) : '-'
        };
      } else if (typeof sub === 'string') {
        subjects[key] = {
          name: formatTitleCase(sub),
          faculty: '-'
        };
      }
    });
  }

  const timetable: Record<string, { t: string; s: string }[]> = {};
  if (parsed.timetable && typeof parsed.timetable === 'object' && !Array.isArray(parsed.timetable)) {
    Object.keys(parsed.timetable).forEach(day => {
      const slots = parsed.timetable[day];
      if (Array.isArray(slots)) {
        timetable[day] = slots
          .filter(slot => slot && typeof slot === 'object' && typeof slot.t === 'string' && typeof slot.s === 'string')
          .map(slot => ({
            t: slot.t.trim(),
            s: slot.s.trim()
          }));
      }
    });
  }

  const config: AppConfig = {
    semesterName,
    subjects,
    timetable,
    minAttendanceReq: typeof parsed.minAttendanceReq === 'number' ? parsed.minAttendanceReq : 75
  };

  return {
    success: true,
    students: sanitizedStudents,
    config
  };
};
